version: '3'

services:
  app:
    build: .
    command: npm run start:docker
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
