version: '3'

services:
  app:
    image: lucassodrem/rest-api-example:app
    build: .
    command: npm run start:docker
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules

  db:
    image: lucassodrem/rest-api-example:db
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: lucassodrem/rest-api-example:adminer
    ports:
      - 8080:8080
